### ISSUE TITLE
我有一个问题。

### ISSUE THREAD

**Issue by accoool** [waimifeier/hikvision-spring-boot-starter#3]
我使用了你的starter。去海康官网下载的win64和linux64的sdk，win调接口都没问题，放到centos上hksdk和PlayCtrl都加载成功了（启动日志里看到加载成功）。但是调同样的接口，就不行。现在不确定是不是sdk版本升级导致的还是其他问题。求指教。

[TID: N/A] 2023-05-12 10:30:02,422 [http-nio-8053-exec-2] ERROR c.n.h.u.HkUtils(100): 设备注册失败：11
[TID: N/A] 2023-05-12 10:30:02,423 [http-nio-8053-exec-2] ERROR c.o.z.o.h.GlobalExceptionHandler(53): 请求地址'/test/login',发生未知异常.
java.lang.RuntimeException: 登陆失败
        at cn.nkk.hikvision.utils.HkUtils.doLogin(HkUtils.java:101)

**Comment by waimifeier** [comment]
下个版本修复

**Comment by accoool** [comment]
或者能告诉我下如何检查问题，还没有搞过c++和 jna的方式

**Comment by accoool** [comment]
跟大佬学习

**Comment by peak666** [comment]
> 我使用了你的starter。去海康官网下载的win64和linux64的sdk，win调接口都没问题，放到centos上hksdk和PlayCtrl都加载成功了（启动日志里看到加载成功）。但是调同样的接口，就不行。现在不确定是不是sdk版本升级导致的还是其他问题。求指教。
> 
> I used your starter. Go To Haikang website to download the Win64 and LINUX64 SDK, WIN adjustment interface is no problem, put on centos HKSDK and PlayCtrl are loaded successfully (boot log see loading success) . But if you tune the same interface, you can't. We are not sure if this is due to an SDK upgrade or some other issue. Please advise.
> 
> [TID: N/A] 2023-05-12 10:30:02,422 [http-nio-8053-exec-2] ERROR c.n.h.u.HkUtils(100): 设备注册失败：11[ TID: N/A ]2023-05-1210:30:02,422[ http-nio-8053-exec-2] ERROR c.n.h.u.HkUtils (100) : 设备注册失败: 11 [TID: N/A] 2023-05-12 10:30:02,423 [http-nio-8053-exec-2] ERROR c.o.z.o.h.GlobalExceptionHandler(53): 请求地址'/test/login',发生未知异常.[ TID: N/A ]2023-05-1210:30:02,423[ http-nio-8053-exec-2] ERROR c.o.o.h. GlobalExceptionHandler (53) : 请求地址’/test/login’，发生未知异常。 java.lang.RuntimeException: 登陆失败Java. Lang. Runtimeexception: Login failed at cn.nkk.hikvision.utils.HkUtils.doLogin(HkUtils.java:101) 请登入 cn.nkk.hikvision.utils.HkUtils.doLogin (HkUtils.java: 101)

请教下win环境本地开发库文件你是怎么放的，为啥我老是提示找不到库文件呢？

**Comment by peak666** [comment]
请问下开发中你是把海康sdk库文件放到哪里去了，为啥我这边老是提示找不到库文件呢，试了很多种方式都不行呢
